### ISSUE TITLE
Invalid pyproject.toml

### ISSUE THREAD

**Issue by raj-mehra** [tcosolutions/blitzdb3#1]
@marcinguy I tried to run the checkmate repo locally and encountered error with this dependency. Something has to do with pyproject.toml file

`Collecting blitzdb3-ce (from -r requirements.txt (line 6))
  Cloning https://github.com/tcosolutions/blitzdb3-ce (to revision main) to /private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-install-soiattuv/blitzdb3-ce_43596b46267747549c3795cd3c06930a
  Running command git clone --filter=blob:none --quiet https://github.com/tcosolutions/blitzdb3-ce /private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-install-soiattuv/blitzdb3-ce_43596b46267747549c3795cd3c06930a
  Resolved https://github.com/tcosolutions/blitzdb3-ce to commit 936dd2ec7e2af53e15c7605c0c964e8ef20351bb
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-build-env-585q48oc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-build-env-585q48oc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-build-env-585q48oc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 92, in <module>
        File "/private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-build-env-585q48oc/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 158, in setup
          dist.parse_config_files()
        File "/private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-build-env-585q48oc/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 606, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-build-env-585q48oc/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 70, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-build-env-585q48oc/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 135, in read_configuration
          validate(subset, filepath)
        File "/private/var/folders/8n/c9n0361j4cj_wtxgrgntckz00000gn/T/pip-build-env-585q48oc/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 59, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `tool.setuptools.packages`.
      configuration error: `tool.setuptools.packages` must be valid exactly by one definition (0 matches found):
      
          - type: array
            items:
              type: string
              at least one of the following:
                - {type: string, format: 'python-module-name-relaxed'}
                - {type: string, format: 'pep561-stub-name'}
          - type: table
            additional keys: False
            keys:
              'find':
                type: table
                additional keys: False
                keys:
                  'where':
                    type: array
                    items: {type: string}
                  'exclude':
                    type: array
                    items: {type: string}
                  'include':
                    type: array
                    items: {type: string}
                  'namespaces': {type: boolean}
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.`

So after successfully cloning, better scan worker image fails during requirement setup.

**Comment by marcinguy** [comment]
Fixed
